[workspace]
authors = ["James Z.M. Gao <gaozm55@gmail.com>"]
channels = ["conda-forge"]
name = "chlibc"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.4-dev"
requires-pixi = ">=0.62.0"

[system-requirements]
# build on centos7
linux = "3.10"
libc = { family = "glibc", version = "2.17" }

# cross toolchain for gcc-x86_64
[feature.gcc-x86_64.system-requirements]
# build on centos7
linux = "3.10"
libc = { family = "glibc", version = "2.17" }

[feature.gcc-x86_64.dependencies]
cmake = ">=4.2"
ninja = "*"
gcc_linux-64 = ">=14" # support C23
[feature.gcc-x86_64.tasks]
_configure-gcc-x86_64 = "cmake --preset gcc-x86_64 -S ."
_build-gcc-x86_64-release = "./cmake-build --preset gcc-x86_64-release"

[environments.gcc-x86-64]
features = ["gcc-x86_64"]
no-default-feature = true
solve-group = "gcc-x86_64"

[tasks]
configure = [
  { task = "_configure-clang-x86_64" },
  { task = "_configure-clang-aarch64" },
  { task = "_configure-gcc-x86_64", environment = "x86-64" },
]
build = [{ task = "build-x86_64" }, { task = "build-aarch64" }]

_configure-clang-x86_64 = "cmake --preset clang-x86_64 -S ."
_configure-clang-aarch64 = "cmake --preset clang-aarch64 -S ."
_configure-clang-riscv64 = "cmake --preset clang-riscv64 -S ."

build-x86_64 = [
  { task = "_build-clang-x86_64-release" },
  { task = "_build-clang-x86_64-debug" },
  { task = "_build-gcc-x86_64-release", environment = "x86_64" },
]
build-aarch64 = [
  { task = "_build-clang-aarch64-release" },
  { task = "_build-clang-aarch64-debug" },
]
build-riscv64 = [
  { task = "_build-clang-riscv64-release" },
  { task = "_build-clang-riscv64-debug" },
]

_build-clang-x86_64-release = "./cmake-build --preset clang-x86_64-release"
_build-clang-x86_64-debug = "./cmake-build --preset clang-x86_64-debug"
_build-clang-aarch64-release = "./cmake-build --preset clang-aarch64-release"
_build-clang-aarch64-debug = "./cmake-build --preset clang-aarch64-debug"
_build-clang-riscv64-release = "./cmake-build --preset clang-riscv64-release"
_build-clang-riscv64-debug = "./cmake-build --preset clang-riscv64-debug"

conda-build = [
  { task = "conda-build-x84_64" },
  { task = "conda-build-aarch64" },
]
conda-build-x84_64 = "CONDA_OVERRIDE_GLIBC=2.17 rattler-build build --output-dir build/output-conda --recipe conda/recipe.yaml --target-platform linux-64"
conda-build-aarch64 = "CONDA_OVERRIDE_GLIBC=2.17 rattler-build build --output-dir build/output-conda --recipe conda/recipe.yaml --target-platform linux-aarch64"

pre-commit-install = "lefthook install"
lint = "lefthook run pre-commit --all-files --no-stage-fixed"
fmt = { cmd = "lefthook run pre-commit --all-files --no-stage-fixed", env = { LEFTHOOK_EXCLUDE = "lint" } }

[dependencies]
cmake = ">=4.2"
ninja = "*"
clang = ">=18"                  # support C23
compiler-rt_linux-64 = "*"
compiler-rt_linux-aarch64 = "*"
lld = "*"
cmakelang = '*'
sysroot_linux-64 = "*"
sysroot_linux-aarch64 = "*"
llvm-tools = "*"
rattler-build = "*"

## riscv64 target cross building is not supported
## package compiler-rt_linux-riscv64 is missing
# sysroot_linux-riscv64 = "*"

lefthook = ">=1.13.1"
pre-commit-hooks = "*"
typos = "*"
taplo = "*"            # lint&format toml
yamlfmt = "*"
clang-tools = "*"
