[workspace]
authors = ["James Z.M. Gao <gaozm55@gmail.com>"]
channels = ["conda-forge"]
name = "chlibc"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
# build on centos7
linux = "3.10"
libc = { family = "glibc", version = "2.17" }

[feature.common.dependencies]
cmake = ">=4"
ninja = "*"
[feature.common.tasks]
configure-arch = "cmake --preset \"$C_ARCH\" -S ."
build-arch = [{task="build-arch-debug"},{task="build-arch-release"}]
build-arch-debug = "./cmake-build --preset \"$C_ARCH\"-debug"
build-arch-release = "./cmake-build --preset \"$C_ARCH\"-release"

# cross toolchain for x86_64
[feature.x86_64.dependencies]
gcc_linux-64 = ">=14" # support C23
[feature.x86_64.activation.env]
C_ARCH = "x86_64"

# cross toolchain for aarch64
[feature.aarch64.dependencies]
gcc_linux-aarch64 = ">=14" # support C23
[feature.aarch64.activation.env]
C_ARCH = "aarch64"

[environments.x86-64]
features = ["common", "x86_64"]
no-default-feature = true
solve-group = "x86_64"

[environments.aarch64]
features = ["common", "aarch64"]
no-default-feature = true
solve-group = "aarch64"

[tasks]
configure = [{task="configure-arch", environment="x86-64"},{task="configure-arch", environment="aarch64"}]

build = [{task="build-x86_64"},{task="build-aarch64"}]
build-x86_64 = [{task="build-arch-debug", environment="x86-64"},{task="build-arch-release", environment="x86-64"}]
build-aarch64 = [{task="build-arch-debug", environment="aarch64"},{task="build-arch-release", environment="aarch64"}]
