detached-environments = false

[mirrors]
"https://repo.prefix.dev/" = ["https://p.qihoo.net/repo.prefix.dev"]
"https://files.pythonhosted.org/packages" = [
  "https://p.qihoo.net/files.pythonhosted.org/packages",
]
"https://github.com/prefix-dev/pixi" = [
  "https://p.qihoo.net/github.com/prefix-dev/pixi",
]
"https://repo.anaconda.com/pkgs" = ["https://p.qihoo.net/conda"]
"https://conda-mapping.prefix.dev/" = [
  "https://p.qihoo.net/conda-mapping.prefix.dev",
]
"https://shards.prefix.dev/" = ["https://p.qihoo.net/shards.prefix.dev"]
"https://conda.anaconda.org/" = ["https://p.qihoo.net/conda"]
"https://prefix.dev/" = ["https://p.qihoo.net/repo.prefix.dev"]
"https://raw.githubusercontent.com/" = [
  "https://p.qihoo.net/raw.githubusercontent.com",
]
