---
c_compiler:
  - clang  # [x86_64 or aarch64]
  - gcc  # [ppc64le]
  - gcc_impl  # [riscv64]
c_compiler_version:
  - ">=18"  # [x86_64 or aarch64]
  - ">=14"  # [ppc64le or riscv64]
c_stdlib:
  - sysroot
c_stdlib_version:  # [linux]
  - "2.17"  # [linux and not riscv64]
  - "2.39"  # [linux and riscv64]
