---
context:
  name: "chlibc"
  version: "0.1.3-dev"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  path: ..

build:
  skip: ${{ target_platform not in ["linux-64", "linux-aarch64"] }}
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist: []
  script:
    content: |
      unset CFLAGS
      unset AR
      unset AS
      unset LD
      unset LDFLAGS
      unset LDFLAGS_LD
      unset OBJCOPY
      unset READELF
      unset STRIP
      unset CMAKE_COLOR_DIAGNOSTICS
      export CC=clang

      env

      cmake --fresh --preset conda-build ${CMAKE_ARGS} -U CMAKE_LINKER -U CMAKE_STRIP
      cmake --build --preset conda-build
      cmake --install build/conda-build

      sha256sum "$PREFIX/bin/chlibc"

requirements:
  build:
    - ${{ compiler('c') }}
    - clang
    - compiler-rt_${{ target_platform }}
    - lld
    - llvm-tools
    - cmake >=4.2
    - ninja
  host:
  run:
    - __glibc

  ignore_run_exports:
    from_package:
      - ${{ compiler('c') }}
    by_name:
      - libgcc

about:
  summary: 'A userspace transparent ld-linux interpreter and glibc swapper.'
  homepage: https://github.com/gzm55/chlibc
  license: MIT
  license_file:
    - LICENSE
