---
schema_version: 1

context:
  release_version: "0.1.6.dev"
  release_hash: 46d6bc9871e03c8296404520c74ab887347a5cab27d3c4d4ca9fa004499ec88d
  is_dev: ${{ env.exists("_CONDA_BUILD_LOCAL") }}
  version: ${{ env.get("PIXI_PROJECT_VERSION") if is_dev else release_version }}


package:
  name: "chlibc"
  version: ${{ version }}

source:
  - if: is_dev
    then:
      path: ..
  - if: not is_dev
    then:
      url: https://github.com/gzm55/chlibc/archive/refs/tags/v${{ version }}.tar.gz
      sha256: ${{ release_hash }}

build:
  skip: ${{ target_platform not in ["linux-64", "linux-aarch64", "linux-ppc64le"] }}
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist: []
  script:
    content: |
      {% if target_platform in ["linux-64", "linux-aarch64"] %}
      unset CFLAGS
      unset AR
      unset AS
      unset LD
      unset LDFLAGS
      unset LDFLAGS_LD
      unset OBJCOPY
      unset READELF
      unset STRIP
      export CC=clang
      {% endif %}

      unset LD_RUN_PATH
      env

      cmake --fresh --preset conda-build ${CMAKE_ARGS} -U CMAKE_LINKER -U CMAKE_STRIP
      cmake --build --preset conda-build --parallel ${CPU_COUNT}
      cmake --install build/conda-build

      sha256sum "$PREFIX/bin/chlibc"

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - cmake >=4.2
    - ninja

    - if: target_platform in ["linux-64", "linux-aarch64"]
      then: clang
    - if: target_platform in ["linux-64", "linux-aarch64"]
      then: compiler-rt_${{ target_platform }}
    - if: target_platform in ["linux-64", "linux-aarch64"]
      then: lld
    - if: target_platform in ["linux-64", "linux-aarch64"]
      then: llvm-tools
    - if: target_platform in ["linux-64", "linux-aarch64"]
      then: clang-tools
  host:
  run:
    - __glibc

  ignore_run_exports:
    from_package:
      - ${{ compiler('c') }}
      - ${{ stdlib('c') }}
    by_name:
      - libgcc
      - __glibc

tests:
  - script:
      - file $PREFIX/bin/chlibc
      - sha256sum $PREFIX/bin/chlibc
      - if: build_platform == target_platform
        then: $PREFIX/bin/chlibc
    requirements:
      build:
        - file
        - coreutils

about:
  summary: 'A userspace transparent ld-linux interpreter and glibc swapper.'
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/gzm55/chlibc

extra:
  recipe-maintainers:
    - gzm55
