---
schema_version: 1

context:
  release_version: "0.1.6"
  release_hash: "ed86a942ee86ba26ec33e8e0cc4dd4f7563674d9df7ce632651425499c7a0d93"
  dev_version: ${{ env.get('PIXI_PROJECT_VERSION') if env.exists('PIXI_PROJECT_VERSION') else '0.0.0.dev' }}
  is_dev: ${{ env.exists('_CONDA_BUILD_LOCAL') }}

package:
  name: "chlibc"
  version: ${{ dev_version if is_dev else release_version }}

source:
  - if: is_dev
    then:
      path: ..
  - if: not is_dev
    then:
      # use the source archive with checksum.txt
      url: https://github.com/gzm55/chlibc/releases/download/v${{ release_version }}/source.tar.gz
      sha256: ${{ release_hash }}

build:
  skip: ${{ target_platform not in ["linux-64", "linux-aarch64", "linux-ppc64le"] }}
  number: 0
  dynamic_linking:
    binary_relocation: false
    rpath_allowlist: []
  script:
    content: |
      {% if target_platform in ["linux-64", "linux-aarch64"] %}
      unset CFLAGS
      unset LDFLAGS
      {% endif %}

      unset LD_RUN_PATH
      env

      cmake --fresh --preset conda-build ${CMAKE_ARGS} -U CMAKE_LINKER -U CMAKE_STRIP
      cmake --build --preset conda-build --parallel ${CPU_COUNT}
      cmake --install build/conda-build

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}

    - cmake >=4.2
    - ninja

    - if: target_platform in ["linux-64", "linux-aarch64"]
      then: compiler-rt_${{ target_platform }}
    - if: target_platform in ["linux-64", "linux-aarch64"]
      then: lld
    - if: target_platform in ["linux-64", "linux-aarch64"]
      then: llvm-tools
    - if: target_platform in ["linux-64", "linux-aarch64"]
      then: clang-tools
  host:
  run:
    - __glibc

  ignore_run_exports:
    from_package:
      - ${{ compiler('c') }}  # do not depend on libgcc
      - ${{ stdlib('c') }}  # do not introduce __glibc version limit

tests:
  - script:
      - file $PREFIX/bin/chlibc
      - sha256sum $PREFIX/bin/chlibc
      - if: build_platform == target_platform
        then: $PREFIX/bin/chlibc
    requirements:
      build:
        - file
        - coreutils
        - zstd

  - if: not is_dev
    then:
      script:
        - echo Verifying the binary checksum
        - |
          case ${{ target_platform }} in
            linux-64)      NATIVE_ARCH="x86_64" ;;
            linux-aarch64) NATIVE_ARCH="aarch64" ;;
            linux-ppc64le) NATIVE_ARCH="ppc64le" ;;
            *)             NATIVE_ARCH="unknown" ;;
          esac
        - EXPECTED_HASH=$(grep "chlibc-$NATIVE_ARCH" checksum.txt | awk '{print $1}')
        - echo "Expected hash $EXPECTED_HASH"
        - echo "$EXPECTED_HASH  $PREFIX/bin/chlibc" | sha256sum -c
      files:
        source:
          - checksum.txt

about:
  summary: 'A userspace transparent ld-linux interpreter and glibc swapper.'
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/gzm55/chlibc

extra:
  recipe-maintainers:
    - gzm55
